
title: Ottawa Civic Tech
hashtag: "#YOWCT"
sub_title: Build civic good.
email: 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

copyright: 'Copyright &copy; 2024. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

description: "Ottawa Civic Tech (#YOWCT) strengthens the community of people in Ottawa who build civic good. We bring together people in policy and technology to solve tough problems and make our communities better."

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/yowcivictech
  - title: youtube
    url: https://www.youtube.com/channel/UCgHMRo-FYS5jw0MnUY75XcQ
  - title: meetup
    url: https://www.meetup.com/YOW_CT/
  - title: github
    url: https://github.com/YOWCT
  - title: trello
    url: https://trello.com/b/LoOLqqad/ottawa-civic-tech-yowct-open-board

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
